theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: true
  menu:
    primary:
      level_2:
        title:
          active: true